---
abstract: 'Detect DjVu file'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DjVu-Detect
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Alien::DjVuLibre: 0.05
  Error::Pure: 0.15
  Exporter: 0
  File::Spec::Functions: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/DjVu-Detect/issues
  homepage: https://github.com/michal-josef-spacek/DjVu-Detect
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/DjVu-Detect
version: '0.06'
